import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import SideBar from "../components/SideBar";
import { Inter as FontSans } from "next/font/google"
import { NextUIProvider } from "@nextui-org/react";
import { SessionProvider } from "next-auth/react";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "File Flush",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} m-0`}>
          {children}
        </body>
      </html>
    </ClerkProvider>

  );
}
