import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import SideBar from "../components/SideBar";
import { Inter as FontSans } from "next/font/google"
import { NextUIProvider } from "@nextui-org/react";
import { SessionProvider } from "next-auth/react";
import AuthProvider from "./components/AuthProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider>
    
      <html lang="en">
      {/* <SessionProvider> */}
        <body className={`${inter.className} m-0`}>
          {/* <AuthProvider> */}
          <div className="flex h-screen w-full ">
            <SideBar />
            <div className="flex flex-col w-full h-full ">
              {children}
            </div>
          </div>
          {/* </AuthProvider> */}
        </body>
        {/* </SessionProvider>   */}
      </html>
      

    </ClerkProvider>

  );
}
